class dto_dados_modelo:
    def __init__(
        self,
        id=None,
        cliid=None,
        IdCliente=None,
        status=None,
        CliLimCredTot=None,
        clisimples=None,
        pedid=None,
        cliMicroEmpreendedor=None,
        CliConsFinal=None,
        HistPagPONTUAL=None,
        HistPagAVISTA=None,
        HistPag8_15=None,
        HistPag16_30=None,
        HistPag31_60=None,
        HistPag_60=None,
        QtConsultado=None,
        RelaFornec0_6Meses=None,
        RelaFornec6Mes_1Ano=None,
        RelaFornec1_3Anos=None,
        RelaFornec3_5Anos=None,
        RelaFornec5_10Anos=None,
        RelaFornec10Anos=None,
        RelaFornecINAT=None,
        PefinNumOcorrencia=None,
        PefinValorTotal=None,
        RefinNumOcorrencia=None,
        RefinValorTotal=None,
        DividasVencNumOcorrencia=None,
        DividasVencValorTotal=None,
        FalenConcNumOcorrencia=None,
        CheqSFundoNumOcorrencia=None,
        RechequeNumOcorrencia=None,
        PartFalenNumOcorrencia=None,
    ):

        self.id = id
        self.cliid = cliid
        self.IdCliente = IdCliente
        self.status = status
        self.pedid = pedid
        self.CliLimCredTot = CliLimCredTot
        self.clisimples = clisimples
        self.cliMicroEmpreendedor = cliMicroEmpreendedor
        self.CliConsFinal = CliConsFinal
        self.HistPagPONTUAL = HistPagPONTUAL
        self.HistPagAVISTA = HistPagAVISTA
        self.HistPag8_15 = HistPag8_15
        self.HistPag16_30 = HistPag16_30
        self.HistPag31_60 = HistPag31_60
        self.HistPag_60 = HistPag_60
        self.QtConsultado = QtConsultado
        self.RelaFornec0_6Meses = RelaFornec0_6Meses
        self.RelaFornec6Mes_1Ano = RelaFornec6Mes_1Ano
        self.RelaFornec1_3Anos = RelaFornec1_3Anos
        self.RelaFornec3_5Anos = RelaFornec3_5Anos
        self.RelaFornec5_10Anos = RelaFornec5_10Anos
        self.RelaFornec10Anos = RelaFornec10Anos
        self.RelaFornecINAT = RelaFornecINAT
        self.PefinNumOcorrencia = PefinNumOcorrencia
        self.PefinValorTotal = PefinValorTotal
        self.RefinNumOcorrencia = RefinNumOcorrencia
        self.RefinValorTotal = RefinValorTotal
        self.DividasVencNumOcorrencia = DividasVencNumOcorrencia
        self.DividasVencValorTotal = DividasVencValorTotal
        self.FalenConcNumOcorrencia = FalenConcNumOcorrencia
        self.CheqSFundoNumOcorrencia = CheqSFundoNumOcorrencia
        self.RechequeNumOcorrencia = RechequeNumOcorrencia
        self.PartFalenNumOcorrencia = PartFalenNumOcorrencia
