name: Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar Dependencias
        run: poetry install

      - name: Conceder permissão de execução ao serviço
        run: chmod +x src/service.py

      - name: Login Docker Hub
        run: echo "${{ secrets.PASSWD_DOCKER }}" | docker login -u "${{ secrets.USR_DOCKER }}" --password-stdin

      - name: Build da imagem
        run: docker build -t ${{ secrets.USR_DOCKER }}/tcc:"$(cat docker-settings.json | jq -r .version)" .

      - name: Enviando imagem ao Docker Hub
        run: docker push ${{ secrets.USR_DOCKER }}/tcc:"$(cat docker-settings.json | jq -r .version)"